version: '3'
networks:
  nw:
services:
  elk:
    container_name: elk
    networks:
       - nw
    build: ./elk
    image: willdurand/elk
    ports:
       - "9200:9200"
       - "8200:80"
       - "5000:5000/tcp"
  configserver:
    container_name: configserver
    networks:
       - nw
    image: test/config-microservices
    restart: always
    ports:
      - "8888:8888"
#    logging:
#      driver: syslog
#      options:
#        syslog-address: udp://192.168.99.100:5000
